@server=http://localhost:4004

@service=/odata/v4/employee-srv

###
GET {{server}}{{service}}/Employee

###
POST {{server}}{{service}}/Employee
Content-Type: application/json

{
    "firstName": "satya1",
    "lastName": "Ranjan1",
    "email": "satya1@gmail.com",
    "phone": 1234
}